_BASE_: denosing_propogation_merge.yaml
MODEL:
  META_ARCHITECTURE: "ClDVIS_offline"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (14000,)
  MAX_ITER: 20000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True

OUTPUT_DIR: './output_CT_ClDVIS_Offline_R50_OVIS'
