_BASE_: CT_ClDVIS_Online_R50_Hard_combine.yaml
MODEL:
  META_ARCHITECTURE: "ClDVIS_offline"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True

OUTPUT_DIR: './output_CT_ClDVIS_Offline_R50_OVIS'
