_BASE_: DVIS_Online_R50.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_offline"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 21
  SAMPLING_FRAME_RANGE: 10
  REVERSE_AGU: True

OUTPUT_DIR: './output_DVIS_Offline_R50_YTVIS19'
