_BASE_: new_online_config.yaml
MODEL:
  META_ARCHITECTURE: "ClDVIS_offline"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True

OUTPUT_DIR: './new_offline_R50_YTVIS19'
