_BASE_: ../DVIS_Plus_Online_R50_4wIter.yaml
MODEL:
  BACKBONE:
    NAME: "D2VitAdapterDinoV2"
  VIT_ADAPTER:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: './work_dirs/dinov2_vitl14_pretrain_.pth'
    FREEZE_VIT: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
DATASETS:
  TEST: ("ytvis_2022_val",)
OUTPUT_DIR: './output_DVIS_Plus_Online_VitAdapterL_YTVIS22_eval'