_BASE_: ../MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "CTMinVIS"
  VIT_ADAPTER:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: 'dinov2_vitl14_pretrain.pth'
    FREEZE_VIT: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_ctdvis"
    NUM_OBJECT_QUERIES: 100
  CL_PLUGIN:
    NUM_NEGATIVES: 99
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (6000, 12000)
  MAX_ITER: 16000
  AMP:
    ENABLED: False

INPUT:
  SAMPLING_FRAME_NUM: 3
  SAMPLING_FRAME_RANGE: 1
  MIN_SIZE_TEST: 480
OUTPUT_DIR: './output_CTVIS_VitAdapterL_YTVIS19'