_BASE_: MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_Plus_online"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvisPlus"
    REID_BRANCH: True
  TRACKER:
    NOISE_MODE: "wa"
    NOISE_RATIO: 0.5

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2

OUTPUT_DIR: './DVIS_Plus_Online_R50_4wIter_YTVIS21'