_BASE_: DVIS_Plus_Online_R50_4wIter.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_Plus_offline"
  REFINER:
    USE_CL: True

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True

OUTPUT_DIR: './DVIS_Plus_Offline_R50_YTVIS21'
