_BASE_: MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "CTMinVIS"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvisPlus"
    REID_BRANCH: True

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00005
  STEPS: (12000, 24000)
  MAX_ITER: 32000

INPUT:
  SAMPLING_FRAME_RANGE: 15
  SAMPLING_FRAME_NUM: 10

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8

OUTPUT_DIR: './output_CTVIS_R50_YTVIS19'