_BASE_: MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "CTMinVIS"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvisPlus"
    REID_BRANCH: True
  CL_PLUGIN:
    NUM_NEGATIVES: 99
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (14000, 18000)
  MAX_ITER: 20000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 720
  CROP:
    ENABLED: False
  PSEUDO:
    CROP:
      ENABLED: False
OUTPUT_DIR: './output_CTVIS_R50_VIPSeg'