_BASE_: DVIS_Online_FC-CLIP_480p_strongAgu.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_offline_OV"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 11
  SAMPLING_FRAME_RANGE: 5
  REVERSE_AGU: True

OUTPUT_DIR: './output_DVIS_Offline_FCCLIP_YTVIS19_480p_strongAgu'