_BASE_: DVIS_Online_supervised_convnextl.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_offline_OV"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 11
  SAMPLING_FRAME_RANGE: 5
  REVERSE_AGU: True

OUTPUT_DIR: './output_OV_DVIS_Offline_supervised_convnextl'