_BASE_: FC-CLIP_onlyCOCO_480p_strongAgu.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_online_OV"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvis_OV"
  TRACKER:
    NOISE_MODE: "wa"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2

DATASETS:
  DATASET_TYPE_TEST: ['video_instance',]
  TEST: ("ytvis_2019_val_21",)

OUTPUT_DIR: './output_Online_ytvis21'