_BASE_: ../DVIS_Offline_zero_shot_convnextl.yaml
MODEL:
  FC_CLIP:
    CLIP_MODEL_NAME: "RN50"
    CLIP_PRETRAINED_WEIGHTS: "openai"
    EMBED_DIM: 1024
    ENSEMBLE_ON_VALID_MASK: True

INPUT:
  SAMPLING_FRAME_NUM: 21
  SAMPLING_FRAME_RANGE: 10
  REVERSE_AGU: True

OUTPUT_DIR: './DVIS_Offline_zero_shot_R50'