_BASE_: ../DVIS_Online_combine_480p_strongAgu.yaml
MODEL:
  FC_CLIP:
    CLIP_MODEL_NAME: "RN50"
    CLIP_PRETRAINED_WEIGHTS: "openai"
    EMBED_DIM: 1024
    ENSEMBLE_ON_VALID_MASK: True

OUTPUT_DIR: './DVIS_Online_combine_480p_R50'