_BASE_: ../CTVIS_R50.yaml
MODEL:
  BACKBONE:
    NAME: "D2VitAdapterDinoV2"
  VIT_ADAPTER:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: './work_dirs/dinov2_vitl14_pretrain_.pth'
    FREEZE_VIT: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
  CL_PLUGIN:
    NUM_NEGATIVES: 199
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (6000, 12000)
  MAX_ITER: 16000

INPUT:
  SAMPLING_FRAME_NUM: 11
  SAMPLING_FRAME_RANGE: 5
OUTPUT_DIR: './output_CTVIS_VitAdapterL_YTVIS21'