_BASE_: DVIS_Plus_Online_R50_4wIter.yaml
MODEL:
  TRACKER:
    NOISE_RATIO: 0.8

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (56000,)
  MAX_ITER: 80000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2

OUTPUT_DIR: './DVIS_Plus_Online_R50_8wIter_YTVIS21'