_BASE_: MinVIS_R50_720p.yaml
MODEL:
  META_ARCHITECTURE: "ClDVIS_online"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_ctdvis"
  TRACKER:
    NOISE_MODE: "hard"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (14000,)
  MAX_ITER: 20000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
  CROP:
    ENABLED: True
  PSEUDO:
    CROP:
      ENABLED: True

OUTPUT_DIR: './output_CT_ClDVIS_Online_R50_VIPSeg_Hard_combine'