_BASE_: DVIS_Plus_Online_R50_4wIter.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_Plus_offline"
  REFINER:
    USE_CL: False

SOLVER:
#  IMS_PER_BATCH: 8
  IMS_PER_BATCH: 4
  STEPS: (28000,)
  MAX_ITER: 45000

INPUT:
  SAMPLING_FRAME_NUM: 17
  SAMPLING_FRAME_RANGE: 8
  REVERSE_AGU: True

OUTPUT_DIR: './DVIS_Plus_Offline_R50_OVIS'
