_BASE_: DVIS_Plus_Online_R50_4wIter.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_Plus_offline"
  REFINER:
    USE_CL: False

SOLVER:
#  IMS_PER_BATCH: 8
  IMS_PER_BATCH: 4
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 43
  SAMPLING_FRAME_RANGE: 21
  REVERSE_AGU: True

#DATASETS:
#  DATASET_RATIO: [1.0, ]
#  DATASET_NEED_MAP: [False, ]
#  DATASET_TYPE: ['video_instance', ]
#  DATASET_TYPE_TEST: ['video_instance', ]
#  # The categories of all datasets will be mapped to the categories of the last dataset
#  TRAIN: ("ovis_train", )
#  TEST: ("ovis_val", )

DATASETS:
  DATASET_RATIO: [0.3, 1.0]
  DATASET_NEED_MAP: [True, False, ]
  DATASET_TYPE: ['image_instance', 'video_instance', ]
  DATASET_TYPE_TEST: ['video_instance', ]
  # The categories of all datasets will be mapped to the categories of the last dataset
  TRAIN: ("coco2ovis_train", "ovis_train")
  TEST: ("ovis_val",)

OUTPUT_DIR: './DVIS_Plus_Offline_R50_OVIS'
