_BASE_: CT_ClDVIS_Online_R50_Hard_combine.yaml
MODEL:
  META_ARCHITECTURE: "ClDVIS_offline"

SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (14000,)
  MAX_ITER: 20000

INPUT:
  SAMPLING_FRAME_NUM: 21
  SAMPLING_FRAME_RANGE: 10
  REVERSE_AGU: True
  CROP:
    ENABLED: True
  PSEUDO:
    CROP:
      ENABLED: True

OUTPUT_DIR: './output_CT_ClDVIS_Offline_R50_VSPW'
