_BASE_: CT_MinVIS_R50.yaml
MODEL:
  META_ARCHITECTURE: "ClDVIS_online"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_ctdvis"
  TRACKER:
    NOISE_MODE: "hard"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2

OUTPUT_DIR: './output_CT_ClDVIS_Online_R50_YTVIS21_Hard_combine'