_BASE_: FC-CLIP_onlyCOCO_480p_strongAgu.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_online_OV"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvis_OV"
  TRACKER:
    NOISE_MODE: "hard"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (35000,)
  MAX_ITER: 50000

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2

OUTPUT_DIR: './output_DVIS_Online_FCCLIP_YTVIS19_480p_strongAgu'