_BASE_: ../CT_ClDVIS_Offline_R50.yaml
MODEL:
  BACKBONE:
    NAME: "D2VitAdapterDinoV2"
  VIT_ADAPTER:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: 'dinov2_vitl14_pretrain.pth'
    FREEZE_VIT: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
SOLVER:
  IMS_PER_BATCH: 8
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TEST: 480
  SAMPLING_FRAME_NUM: 21
  SAMPLING_FRAME_RANGE: 10
OUTPUT_DIR: './output_CT_ClDVIS_Offline_VitAdapterL_OVIS'