_BASE_: ../CT_ClDVIS_Online_R50_Hard_combine.yaml
MODEL:
  BACKBONE:
    NAME: "D2VitAdapterDinoV2"
  VIT_ADAPTER:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: 'dinov2_vitl14_pretrain.pth'
    FREEZE_VIT: True
  TRACKER:
    USE_CL: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
SOLVER:
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TEST: 480
OUTPUT_DIR: './output_CT_ClDVIS_Online_VitAdapterL_OVIS'